export const navlink = [
  { id: 1, title: "หาน้อง", slug: "/" },
  { id: 2, title: "เจอน้อง", slug: "/founddog" },
];

export const dogSpecies = [
  "เกรทเดน  Great Dane",
  "เกรทเทอร์ สวิสส์ เมาน์เทนด๊อก  Greater Swiss Mountain Dogs",
  "โกลเด้น รีทรีฟเวอร์  Golden Retriever",
  "คอเคเซียน เชพเพิร์ด  Caucasian Shepherd",
  "คอลลี่ Collie",
  "คาวาเลียร์ คิง ชาลส์ สแปเนียล  Cavalier King Charles Spaniel",
  "คีชอน  Keeshounds",
  "เคน คอร์โซ่  Cane Corso",
  "เครนเทอร์เรีย  Cairn Terrier",
  "เคอร์รี บลู เทอร์เรีย  Kerry Blue Terriers",
  "โคมอนดอร์   Komondor",
  "เจแปนนิส ชิน  Japanese Chins",
  "เจแปนนิส สปิตซ์  Japanese Spitz",
  "แจ็ครัสเซลล์เทอร์เรีย  Jack Russell Terrier",
  "ชเนาเซอร์  Schnauzer",
  "ชาเป่ย  Sharpei",
  "ชิบะ อินุ  Shiba Inu",
  "ชิวาวา  Chihuahua",
  "ชิสุ  ShihTzu",
  "เชดแลนด์ชิพด๊อก   Shetland Sheepdog",
  "เชา เชา  Chow Chow",
  "ไชนีส เครสเต็ด   Chinese Crested",
  "ซามอยด์  Samoyed",
  "ซาลูกิ  Saluki",
  "เซนต์เบอร์นาร์ด  St. Bernard",
  "เซาท์ แอฟริกัน มาสทิฟฟ์ (บัวโบว์)  South African Mastiff (Boerboel)",
  "ไซบีเรียน ฮัสกี้  Siberian Husky",
  "ดัชชุน  Dachshund",
  "ดัลเมเชียน  Dalmatian",
  "โดเบอร์แมน  Doberman Pinscher",
  "ทิเบตัน มาสทิฟฟ์  Tibetan Mastiff",
  "ไทยบางแก้ว  Thai Bangkaew",
  "ไทยหลังอาน  Thai Ridgeback",
  "นโปเลียน มาสทิฟฟ์   Neapolitan Mastiff",
  "บริตทานีสแปเนียล  Brittany Spaniel",
  "บลัดฮาวด์  Bloodhound",
  "บ็อกเซอร์  Boxer",
  "บอร์ซอย  Borzoi",
  "บอสตัน เทอร์เรียร์  Boston Terrier",
  "บาเซ็นจิ  Basenji",
  "บาสเซ็ต ฮาวด์  Basset Hound",
  "บิชอง ฟริเซ่  Bichon Frisé",
  "บีเกิล  Beagle",
  "บูลล์เทอร์เรีย  Bull Terrier",
  "เบดลิงตัน เทอร์เรียร์  Bedlington Terrier",
  "เบอร์นีส เมาน์เทนด็อก  Bernese Mountain Dog",
  "โบโลเนส  Bolognese",
  "ปอมเมอเรเนียน  Pomeranian",
  "ปักกิ่ง  Pekingese",
  "ปั๊ก  Pug",
  "ปาปิยอง  Papillon",
  "ปูมิ  Pumi",
  "พ็อมโบรค เวล์ช คอร์กี้  Pembroke Welsh Corgi",
  "พุดเดิ้ล  Poodle",
  "เฟรนช์ บูลด็อก  French Bulldog",
  "มอลทีส  Maltese",
  "มิเนเจอร์พินช์เชอร์  Miniature Pinscher",
  "ยอร์คเชียร์เทอร์เรีย  Yorkshire Terrier",
  "เยอรมัน สปิตซ์   German Spitz",
  "เยอรมันเชฟเฟิร์ด  German Shepherd",
  "ร็อตไวเลอร์  Rottweiler",
  "ลาบราดอร์รีทรีฟเวอร์  Labrador Retriever",
  "วิซสลา  Vizsla",
  "วิปเพ็ท  Whippet",
  "เวสตี้ เทอร์เรียร์  Westie Terrier",
  "ไวมาราเนอร์  Weimaraner",
  "สกาย เทอร์เรีย  Skye Terrier",
  "สมูธ ฟ็อกซ์ เทอร์เรีย  Smooth Fox Terrier",
  "อเมริกัน ค็อกเกอร์  American Cocker Spaniel",
  "อเมริกัน พิทบูลเทอร์เรีย  American Pit Bull Terrier",
  "อเมริกัน เอสกิโม  American Eskimo",
  "อเมริกันบูลล์ด็อก  American Bulldog",
  "อลาสกัน มาลามิวท์  Alaskan Malamute",
  "ออสเตรเลียน เชพเฟิร์ด   Australian Shepherd",
  "อัฟกัน ฮาวนด์  Afghan Hound",
  "อาคิตะ อินุ  Japanese Akita Inu",
  "อิงลิช บูลล์ด็อก  English Bulldogs",
  "อิตาเลียน เกรย์ฮาวด์  Italian Greyhound",
  "โอลด์อิงลิชชีปด็อก  Old English Sheepdog",
  "ไอริช วูล์ฟฮาวน์ด   Irish Wolfhound",
  "พันธุ์ผสม  Mixedbreed dog",
].map((breed) => {
  return { value: breed, label: breed };
});

const area = {
  พระนคร: ["พระบรมมหาราชวัง"],
};
